# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls_collector.Document')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('documents', models.ManyToManyField(through='urls_collector.Occurence', to='urls_collector.Document')),
            ],
        ),
        migrations.AddField(
            model_name='occurence',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls_collector.URL'),
        ),
        migrations.AddField(
            model_name='document',
            name='urls',
            field=models.ManyToManyField(through='urls_collector.Occurence', to='urls_collector.URL'),
        ),
    ]
