# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(db_index=True, max_length=2000, unique=True),
        ),
    ]
